x-backend:
  &backend
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    RAILS_ENV: development
    POSTGRES_USER: postgres
    REDIS_URL: redis://redis:6379/1
    DB_HOST: db


  restart: on-failure:3
  volumes:
    - .:/backend:rw
    - bundle_cache:/bundle
services:
  backend:
    <<: *backend
    stdin_open: true
    tty: true
    ports:
      - 3000:3000/tcp
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated

  redis:
    image: 'redis:7.2.4'
    command: redis-server
    volumes:
      - redis:/data

volumes:
  bundle_cache:
  postgresql:
  redis:
